name: Continuous integration
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - run: docker build . -f test/Dockerfile
